### ISSUE TITLE
Switch ClientApplicationSettings to EncryptedExtensions

### ISSUE THREAD

**Issue by davidben** [vasilvv/tls-alps#2]
@ekr suggested that ClientApplicationSettings should just be EncryptedExtensions. That seems reasonable, though we'd have to answer a few questions:

1. Which extensions can be sent in client EncryptedExtensions? My inclination is you can send an extension in client EE if it was advertised in server EE. Server EE extensions, in turn, need to be sent in ClientHello, though we've been muttering about changing that. Unclear to me whether that should be the same mechanism that signals client EE or orthogonal.

2. When can the client send it? When must the client send it? When does the server accept it? When must the server accept it? The main requirement is servers that don't know about client EE must not see it. Some possibilities:

   * Client MUST send it if the server negotiated some extension which uses it. Server expects it if and only if the client was supposed to send it. This is deterministic and minimal, but implementations need to keep track of all extensions that use it. (Column in IANA table?)
   * Server MUST accept an optional client EE in all connections. If missing, interpret as empty. Clients always go through the motions of assembling it, but if it turns out to be empty, they SHOULD or MUST omit it. Either servers tolerate empty ones or reject them, depending on which we want. If they reject empty ones, this is *almost* the same as the above, except when some extension makes the client EE extension optional. This also potentially adds an optional mode to existing handshakes and adds optional messages, which I don't like.
    * There's some separate extension the client sends which implies client EE is included. Maybe tie in unsolicited server EE extensions if we want to here. I'm not a huge fan of this option because we'd need to deal with correlating ALPS and other client-EE-using extensions with this extension anyway.
    * TLS 1.4??? (This is not a serious suggestion. I think. Though we should probably simplify this in 1.4 when we do it.)

Note some of these options mess up half-RTT tickets, if the server can no longer predict the client's second flight. (See #1.)

**Comment by vasilvv** [comment]
> Which extensions can be sent in client EncryptedExtensions? My inclination is you can send an extension in client EE if it was advertised in server EE.

Agreed.

> Client MUST send it if the server negotiated some extension which uses it. Server expects it if and only if the client was supposed to send it. This is deterministic and minimal, but implementations need to keep track of all extensions that use it.

I think this is probably the approach I like the most here.
